export const EVENT_CONFIG = {
  name: "Café de Conexões e Negócios",
  tagline: "Um dia exclusivo de estratégias, networking e experiências premium nesse espaço maravilhoso",
  date: "15 de Agosto de 2026",
  dateISO: "2026-08-15",
  dayOfWeek: "Sábado",
  startTime: "10:00",
  endTime: "20:30",
  totalSpots: 40,
  location: {
    name: "Espaço Premium",
    address: "Av. Pedroso de Morais, 2548",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Av.+Pedroso+de+Morais,+2548+-+Sao+Paulo,+SP",
    wazeUrl: "https://waze.com/ul?q=Av.%20Pedroso%20de%20Morais,%202548,%20Sao%20Paulo",
  },
  host: {
    name: "Gabi Artz",
  },
  timeline: [
    {
      time: "10:00",
      title: "Café de Boas-vindas",
      description: "Recepção com coffee e networking inicial",
      icon: "coffee",
    },
    {
      time: "11:00",
      title: "Apresentações",
      description: "Dinâmica estratégica",
      icon: "target",
    },
    {
      time: "13:00",
      title: "Networking Intencional",
      description: "Brunch",
      icon: "users",
    },
    {
      time: "15:00",
      title: "Conteúdo Exclusivo",
      description: "Uma experiência que você não pode perder",
      icon: "gift",
    },
    {
      time: "16:00",
      title: "Momento Fotos e Vídeos na Casa",
      description: "Tempo para tirar fotos e gravar vídeos que vão te posicionar como autoridade",
      icon: "camera",
    },
    {
      time: "17:00",
      title: "Surpresa Especial",
      description: "Prepare-se para o inesperado",
      icon: "sparkles",
    },
    {
      time: "18:30",
      title: "Happy Hour",
      description: "Celebração e networking descontraído",
      icon: "wine",
    },
    {
      time: "20:30",
      title: "Jantar All Exclusive",
      description: "Jantar exclusivo com Chef de Cozinha",
      icon: "utensils",
    },
  ],
  hotels: [
    {
      name: "Hotel Emiliano",
      stars: 5,
      distance: "1.2 km",
      address: "Rua Oscar Freire, 384 - Jardins",
      phone: "(11) 3068-4399",
      website: "https://emiliano.com.br",
      priceRange: "$$$$$",
    },
    {
      name: "Hotel Fasano",
      stars: 5,
      distance: "1.5 km",
      address: "Rua Vittorio Fasano, 88 - Jardins",
      phone: "(11) 3896-4000",
      website: "https://fasano.com.br",
      priceRange: "$$$$$",
    },
    {
      name: "Tivoli Mofarrej",
      stars: 5,
      distance: "2.0 km",
      address: "Al. Santos, 1437 - Cerqueira César",
      phone: "(11) 3146-5900",
      website: "https://tivolihotels.com",
      priceRange: "$$$$",
    },
    {
      name: "Renaissance São Paulo",
      stars: 5,
      distance: "2.5 km",
      address: "Al. Santos, 2233 - Cerqueira César",
      phone: "(11) 3069-2233",
      website: "https://marriott.com",
      priceRange: "$$$$",
    },
    {
      name: "Ibis Styles Faria Lima",
      stars: 3,
      distance: "0.8 km",
      address: "Av. Brigadeiro Faria Lima, 2534",
      phone: "(11) 3093-4600",
      website: "https://ibis.accor.com",
      priceRange: "$$",
    },
  ],
  airports: [
    {
      name: "Aeroporto de Congonhas (CGH)",
      code: "CGH",
      distance: "8 km",
      travelTime: "20-40 min",
      directions: "Siga pela Av. Washington Luís até a Marginal Pinheiros. Siga norte pela Marginal e saia na Av. Faria Lima. Continue até a Av. Pedroso de Morais.",
      uber: "Aproximadamente R$ 35-50",
      taxi: "Aproximadamente R$ 60-80",
    },
    {
      name: "Aeroporto de Guarulhos (GRU)",
      code: "GRU",
      distance: "35 km",
      travelTime: "45-90 min",
      directions: "Siga pela Rod. Hélio Smidt até a Rod. Ayrton Senna. Continue pela Marginal Tietê e depois Marginal Pinheiros sentido sul. Saia na Av. Faria Lima.",
      uber: "Aproximadamente R$ 100-150",
      taxi: "Aproximadamente R$ 150-200",
      shuttle: "Airport Bus Service até o Terminal Tietê, depois metrô ou Uber",
    },
  ],
  dressCode: {
    style: "Business Casual",
    note: "Ou como você se sentir mais à vontade. O importante é se sentir bem e ser autêntico.",
    feminine: [
      {
        description: "Sapatilha, calça jeans e camisa",
        image: "/dress-code/feminine-1.jpg",
      },
      {
        description: "Vestido, bota e jaqueta",
        image: "/dress-code/feminine-2.jpg",
      },
      {
        description: "Terno profissional",
        image: "/dress-code/feminine-3.jpg",
      },
    ],
    masculine: [
      {
        description: "Calça social e camiseta",
        image: "/dress-code/masculine-1.jpg",
      },
      {
        description: "Terno e gravata",
        image: "/dress-code/masculine-2.jpg",
      },
      {
        description: "Calça jeans e camisa",
        image: "/dress-code/masculine-3.jpg",
      },
    ],
  },
};

export type EventConfig = typeof EVENT_CONFIG;
